export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const SUBSCRIBE_SUCCESS = 'SUBSCRIBE_SUCCESS';
export const REMOVE_SUBSCRIPTION = 'REMOVE_SUBSCRIPTION';
export const GET_SUBSCRIBED_GAMES = 'GET_SUBSCRIBED_GAMES';
export const GET_GAMES = 'GET_GAMES';